### ISSUE TITLE
connection specific DNS suffix

### ISSUE THREAD

**Issue by gvde** [eduvpn/vpn-server-node#35]
It's possible to set DNS servers in a vpnprofile but not a connection specific domain name nor a domain search list.

It would be nice if that was possible to get something like

push "dhcp-option DOMAIN example.com"
push "dhcp-option DOMAIN-SEARCH example.org"
push "dhcp-option DOMAIN-SEARCH example.com"

into the openvpn server configuration...

**Comment by fkooman** [comment]
Nice idea! 

> push "dhcp-option DOMAIN-SEARCH example.org"

This doesn't seem to be a valid option according to the OpenVPN manpage, are you sure this works?

**Comment by gvde** [comment]
It's seems some client implementations support it. I have tested in on MacOS and it works.

Runs through this script: https://github.com/eduvpn/macos/blob/master/openvpn-2.4.7-openssl-1.1.1b/client.up.eduvpn.sh

On Linux it seems to be multiple DOMAIN options to do build the search list: https://github.com/OpenVPN/openvpn/blob/master/contrib/pull-resolv-conf/client.up

Haven't checked on other systems.

**Comment by fkooman** [comment]
Right. It seems only `DOMAIN` has broader support. So I'd propose making a configuration option called `dnsSuffix` that takes an array where you can set multiple domains. What do you think? Who will test this on all the different platforms? :-)

**Comment by gvde** [comment]
It‘s not so much a platform problem but a client side issue and what scripts are used. I guess all eduVPN/let‘s connect clients should consistently handle the dhcp options...

**Comment by fkooman** [comment]
> It‘s not so much a platform problem but a client side issue and what scripts are used. I guess all eduVPN/let‘s connect clients should consistently handle the dhcp options...

Yeah, that is a good idea. I also have to look at what the other OpenVPN clients do, e.g. NetworkManager-openvpn on Linux only support multiple DOMAIN entries for example, I'm testing Windows OpenVPN now...

**Comment by fkooman** [comment]
On Windows (eduVPN/OpenVPN) it takes the last one if you push multiple DOMAIN options.

**Comment by fkooman** [comment]
Viscosity (on Windows) *does* support multiple DOMAIN options.

**Comment by fkooman** [comment]
So whatever way we go, I think we should use only `DOMAIN` and allow for multiple domains to be specified and fix the clients that do not (yet) work this way, if multiple `DOMAIN` options are actually important...?

**Comment by gvde** [comment]
That may work for the moment. In the long run it should match how probably all platforms handle it:

domain is the domain name for the connection (added to the host name)

search is a list of domain names used to search for FQDNs when none is given.

The search list is the domain name if not specified.

Linux/MacOS/Windows have this. I suppose the mobile platforms won’t be so different.

**Comment by fkooman** [comment]
* https://github.com/eduvpn/vpn-lib-common/commit/32bb539210287d41a6707ee14304f378ae4a329e
* https://github.com/eduvpn/vpn-server-node/commit/7e40ed0ba5ee898c7af203a83a7da2f3df926db0
* https://github.com/eduvpn/vpn-server-api/commit/defbc5cae9bd5e181ee0cecd5ffe532374a0d33c

Will be part of the next update(s) to the 2.x branch.

**Comment by fkooman** [comment]
Release is available: https://list.surfnet.nl/pipermail/eduvpn-deploy/2019-August/000157.html

Windows client [issue](https://github.com/Amebis/eduVPN/issues/110)
