### ISSUE TITLE
Configure syslog progname for openvpn server files

### ISSUE THREAD

**Issue by gvde** [eduvpn/vpn-server-node#37]
Currently all configured openvpn servers use syslog logging and use "openvpn" as prefix. If you have multiple openvpn instances, e.g. for tcp and udp or with different ports it's not possible to distinguish log message of instances.

It would be nice if the generated config includes a syslog option adding the instance name to distinguish instance log messages, e.g.

syslog openvpn-internet-0

**Comment by fkooman** [comment]
```systemctl edit --full "openvpn-server@.service"
```

Add `--syslog openvpn-server@%i` somewhere after `ExecStart`.

```
systemctl disable --now openvpn-server@internet-{0,1}.service
systemctl enable --now openvpn-server@internet-{0,1}.service
```

I think this would be a pretty good addition to the (default) OpenVPN systemd unit file! Maybe you can open an issue there?

**Comment by fkooman** [comment]
https://github.com/OpenVPN/openvpn/blob/master/distro/systemd/openvpn-server@.service.in

**Comment by gvde** [comment]
> ```
> systemctl edit --full "openvpn-server@.service"
> ```
> 
> Add `--syslog openvpn-server@%i` somewhere after `ExecStart`.
> 
> ```
> systemctl disable --now openvpn-server@internet-{0,1}.service
> systemctl enable --now openvpn-server@internet-{0,1}.service
> ```
> 
> I think this would be a pretty good addition to the (default) OpenVPN systemd unit file! Maybe you can open an issue there?

I am not sure if that works too well with various other logging options in openvpn, e.g. if the config file  configures a log file instead of syslog. Could be quiet confusing if some parts are on command-line from systemd file while everything else is in the config file...

**Comment by fkooman** [comment]
Afaik the config file overrides the options on the command line...

**Comment by gvde** [comment]
> Afaik the config file overrides the options on the command line...

Yes. But it seems wrong to me to change some settings if not necessary. I think people using openvpn itself will often only have a single profile.

With eduvpn you usually start out with two (one for tcp and one for udp) and have even more.

So I think in general, it should be the choice of the admin what syslog tag to use when using openvpn directly.

For eduvpn installations it would make things easier if it is automatically changed or at least a configuration option is available to set it. eduvpn users don't want to know about openvpn in all details thus some help at that point would be good...

**Comment by fkooman** [comment]
I'm just thinking bigger picture here, it could actually be really helpful for upstream to have the name of the config mentioned in the syslog as well, even if there is only 1 profile... this is also true for OpenVPN clients I guess...

**Comment by gvde** [comment]
But to use openvpn you'll need to write the config file anyway. There is no default installed config only lot's of example file which covers all areas including logging. So if you use openvpn you'll kind of get past the logging settings at some point. With eduvpn you usually won't...

**Comment by fkooman** [comment]
https://patchwork.openvpn.net/patch/806/

Let's see what they say...

**Comment by fkooman** [comment]
https://sourceforge.net/p/openvpn/mailman/message/36740999/

Is that helpful?

**Comment by gvde** [comment]
O.K. That's true. I usually look into /var/log/messages (the old fashioned way). With journalctl you'll get instance specific logs.

Of course, if you don't know the instance to look for then it's still cumbersome. You'll have to try all possible instances to find which instance it is.
