### ISSUE TITLE
The wrong subnet is configured if `range` is not set to the network address

### ISSUE THREAD

**Issue by jornane** [eduvpn/vpn-server-node#38]
If the range is set to `192.0.2.64/25` with two OpenVPN instances, these are configured with subnets `192.0.2.64/26` and `192.0.2.128/26`. This is wrong, because `192.0.2.128/26` is not inside `192.0.2.64/25`.

**Comment by jornane** [comment]
The error occurs in both `vpn-server-node-server-config` and `vpn-server-node-generate-dns-zones`, so I guess this is an error in a library.

**Comment by fkooman** [comment]
I think this is fixed now in https://github.com/eduvpn/vpn-server-node/commit/fa3d4e14348bb3ced437ae574114cd1e318fca0c

**Comment by fkooman** [comment]
This was also broken for IPv6, but now fixed in #43
