### ISSUE TITLE
support openvpn-nl

### ISSUE THREAD

**Issue by fkooman** [eduvpn/vpn-server-node#4]
1. `tls-ciphers` is not supported;
2. only 2048 bit DH is supported (currently we have 4096);

we can introduce a `isOpenVpnNl` or something configuration directive that would take care of that, OR we could just remove the `tls-ciphers` directive altogether and switch to DH of 2048 which should be secure enough anyway.

**Comment by fkooman** [comment]
with `tls-ciphers` removed, a DH of size 2048 and a lot of patience while the OpenVPN-nl processes gathered enough entropy it works without modifying the client configuration.

**Comment by fkooman** [comment]
also with the eduVPN android app

**Comment by sveeke** [comment]
Why not also ask Fox to add 4096 bit DH support? Especially with OpenVPN-NL we should not scrimp on keysize.

**Comment by fkooman** [comment]
@sveeke will you talk to them about adding this support? And maybe you can ask them about their plans for OpenVPN 2.4...

**Comment by fkooman** [comment]
We deviated too far, maybe when OpenVPN-nl 2.4 is released we can revisit this.
