### ISSUE TITLE
vpn-maint-apply-changes enables \x2a instance (*) when no profiles available

### ISSUE THREAD

**Issue by jornane** [eduvpn/vpn-server-node#49]
When running `vpn-maint-apply-changes` when `/etc/vpn-server-node/config.php` does not contain an existing profile name in profileList, the script enables the service `openvpn-server@\x2a.service`. `\x2a` is `*` escaped.

	# /usr/sbin/vpn-maint-apply-changes
	Invalid unit name "openvpn-server@*" was escaped as "openvpn-server@\x2a" (maybe you should use systemd-escape?)
	Created symlink /etc/systemd/system/multi-user.target.wants/openvpn-server@\x2a.service → /lib/systemd/system/openvpn-server@.service.
	Job for openvpn-server@\x2a.service failed because the control process exited with error code.
	See "systemctl status "openvpn-server@\\x2a.service"" and "journalctl -xe" for details.

**Comment by fkooman** [comment]
This issue belongs here: https://github.com/letsconnectvpn/vpn-maint-scripts/issues ? 

Hmm... it seems the `for` loop does not work as expected? if nothing matches it gives back the result with the "*" in it?

https://github.com/letsconnectvpn/vpn-maint-scripts/blob/2a965b83499a389390a300123633babde2b13bdd/bin/vpn-maint-apply-changes#L20

**Comment by fkooman** [comment]
Something like this instead would work:

```
for CONFIG_NAME in $(find /etc/openvpn/server -type f -name *.conf); do echo $CONFIG_NAME; done
```

**Comment by jornane** [comment]
> This issue belongs here: https://github.com/letsconnectvpn/vpn-maint-scripts/issues ?

Feel free to move the issue, I didn't know about the letsconnectvpn group, I was wondering where the script came from.

> Hmm... it seems the `for` loop does not work as expected? if nothing matches it gives back the result with the "*" in it?

That is the default behaviour of `sh`, globbing uses `*` to match file names, but if there are no matches it returns a literal `*`. Test this by running `echo *` in an empty and a filled directory.

See [Why is nullglob not default](https://unix.stackexchange.com/questions/204803/why-is-nullglob-not-default) on Stack Exchange for more information. You may also consider using `failglob`, if the Linux shell supports it (I did not test this).

**Comment by fkooman** [comment]
> Feel free to move the issue, I didn't know about the letsconnectvpn group, I was wondering where the script came from.

Doesn't seem possible...

> That is the default behaviour of sh, globbing uses * to match file names, but if there are no matches it returns a literal *. Test this by running echo * in an empty and a filled directory.
> 
> See Why is nullglob not default on Stack Exchange for more information. You may also consider using failglob, if the Linux shell supports it (I did not test this).

Wow... Let's keep it simple and just use use `ls /etc/openvpn/server | grep \.conf$` instead :-)

**Comment by fkooman** [comment]
I also ran into this: https://github.com/koalaman/shellcheck/wiki/SC2010  not sure if that is better/nicer...

**Comment by fkooman** [comment]
Closed via https://github.com/letsconnectvpn/vpn-maint-scripts/commit/a9e3eabb0ac7b49721ecb77544e4220933c07ba6

Thanks!
